# Site wide configuration

title: Geek Out
locale: pt_BR
description: O podcast para geeks conectad@s
logo: geekout_round_300x300.png
search: false
url: 


# Jekyll configuration

permalink:   /:year/:month/:day/:title.html
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# iTunes specific configs
itunes_summary: "Geek Out - O podcast para geeks conectad@s"
itunes_url: 
itunes_big_image: "/images/geekout-logo-1400x1400.png"
itunes_default_image: "/images/geekout_round_300x300.png"
base_url: http://geekout.fm

# Site owner
owner:
  name: "Geek Out Podcast"
  avatar: bio-photo.jpg
  email: contato@geekout.fm
  disqus-shortname:
  twitter: geekoutfm
  facebook: geekoutfm
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify: